### ISSUE TITLE
'hb_EPFenSurface' object has no attribute 'shade material'

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#526]
Hello,

I updated today my defintion and this error came out:
![image](https://cloud.githubusercontent.com/assets/8501837/16680468/efee17ee-44ee-11e6-8bc3-3af806bace7c.png)
I guess it has something to do with shading.

**Comment by jacoposartore** [comment]
The error is caused by the grazing based on ratio component: if I bypass it, the simulation runs.

**Comment by chriswmackey** [comment]
@jacoposartore ,

Thanks for reporting this.  It was a really stupid bug on my part that I have just fixed:
https://github.com/mostaphaRoudsari/Honeybee/commit/b78cc15038d04c8407e527835f9d2f347a9d883a

Thanks again
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey ,

thank you very much!

**Comment by jacoposartore** [comment]
@chriswmackey,

i have updated my definition and I still have the same error, now also with Openstudio.

**Comment by jacoposartore** [comment]
I tried with a file from scratch and I get the same error.

![image](https://cloud.githubusercontent.com/assets/8501837/16758680/63f2f9bc-4813-11e6-9b31-90c41d221bde.png)

**Comment by chriswmackey** [comment]
@jacoposartore ,

Try now after this change that I just made and let me kno:
https://github.com/mostaphaRoudsari/Honeybee/commit/0e41a76a8d7db143e5919c466e70bb6d43902918

**Comment by chriswmackey** [comment]
Yes, I am 99.9% positive that the commit I posted there fixes this.

**Comment by jacoposartore** [comment]
@chriswmackey,

Great! Now everything works fine!
Thank you!

**Comment by chriswmackey** [comment]
Glad to hear it and thanks, again!
